<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "freewall"
 *
 * Auto generated by Extension Builder 2015-01-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FreeWall',
	'description' => 'Flexibel Grid Layout for Image Gallery',
	'category' => 'plugin',
	'author' => 'Juri Kostik',
	'author_email' => 'juri.kostik@web-se.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => true,
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);